# use only absolute path !
system:
    # command for stop/start/status of your webservice (apache2, nginx, etc.)
    ws-stop:  "/etc/init.d/nginx stop"
    ws-start: "/etc/init.d/nginx start"
    ws-status: "/etc/init.d/nginx status"
    # where is letsencrypt-auto script installed
    le-script:   "/opt/letsencrypt/"
    # directory path where are names of domains names like directory, containing certificates
    le-domains:  "/etc/letsencrypt/live/"
    # admin email for any warns and errors
    admin-email:  "name@domain.com"


